# Assumes the caller has setup the environment and built the packages
name: Publish packages
description: Publishes packages.
inputs:
  NODE_AUTH_TOKEN:
    description: "NPM automation token with publish access for the @canonical npmjs org"
    required: true
runs:
  using: composite
  steps:
    # Consumes NODE_AUTH_TOKEN from the environment to authenticate with NPM
    - name: Authenticate with NPM registry
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}

    - name: Publish packages
      shell: bash
      run: lerna publish --yes --no-private from-package
