name: Setup environment
description: Installs build tools and dependencies
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      shell: bash
      run: bun install
