name: "react-ds-core/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - configs/typescript-base/**
      - configs/typescript-react/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-core/**
      - packages/react/ds-core-form/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_CORE }}
    with:
      working-directory: packages/react/ds-core
      externals: '[
        "configs/storybook/**",
        "configs/typescript-base/**",
        "configs/typescript-react/**",
        "packages/styles/**",
        "packages/utils/**"
      ]'