name: "ds-react-core-form/Publish to chromatic"
on:
  push:
    branches:
      - '**'  # This excludes tags
    paths: [packages/react/ds-core-form/**]
defaults:
  run:
    working-directory: packages/react/ds-core-form
jobs:
  test-compile:
    uses: ./.github/workflows/_chromatic.yaml
    secrets:
      PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_CORE }}
    with:
      working-directory: packages/react/ds-core-form
