name: "ds-react-app-launchpad/Publish to chromatic"
on:
  pull_request:
    paths: [packages/react/ds-app-launchpad/**]
defaults:
  run:
    working-directory: packages/react/ds-app-launchpad
jobs:
  test-compile:
    uses: ./.github/workflows/_chromatic.yaml
    secrets:
      PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_APP_LAUNCHPAD }}
    with:
      working-directory: packages/react/ds-app-launchpad
