name: "Pull request"
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build all packages
        run: bun run build

      - name: Run tests
        run: bun run test

  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check inclusive naming
        uses: canonical/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail-on-error: true
